version: "{build}"

os:
  - Visual Studio 2017
  - Visual Studio 2015
  - Visual Studio 2013

environment:
  matrix:
    - additional_flags: "/std:c++latest"
      wmain: 0

matrix:
  exclude:
    - additional_flags: "/permissive- /std:c++latest"
      os: Visual Studio 2015
    - additional_flags: "/permissive- /std:c++latest"
      os: Visual Studio 2013

init:
  - git config --global core.autocrlf input
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

shallow_clone: true

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - set CXXFLAGS=%additional_flags%
  - cmake -H. -Bbuild -A%PLATFORM% -DUSE_WMAIN=%wmain%

# build with MSBuild
build:
  project: build\CatchSelfTest.sln      # path to Visual Studio solution or project
  verbosity: normal                     # MSBuild verbosity level {quiet|minimal|normal|detailed}

test_script:
  - cd build
  - ctest -V -j 2 -C %CONFIGURATION%