version: "{build}"

os:
  - Visual Studio 2017
  - Visual Studio 2015
  - Visual Studio 2013

environment:
  matrix:
    - additional_flags: "/std:c++latest"

matrix:
  exclude:
    - additional_flags: "/permissive- /std:c++latest"
      os: Visual Studio 2015
    - additional_flags: "/permissive- /std:c++latest"
      os: Visual Studio 2013

init:
  - git config --global core.autocrlf input
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

shallow_clone: true

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - set CXXFLAGS=%additional_flags%
  - cmake -H. -Bbuild -A%PLATFORM%
  - cd build

build:
  project: Project.sln
  parallel: true
  verbosity: normal

build_script:
  - cmake --build .

test_script:
  - ctest -V -j 2 -C %CONFIGURATION%